In [33]:
import tensorflow_hub as hub
import tensorflow as tf
from numpy import dot
from numpy.linalg import norm
# import os
# encoder = hub.load('https://tfhub.dev/google/universal-sentence-encoder/4')
# Load the model
model_path = "universal-sentence-encoder-large_5"
encoder = hub.load(model_path)


def embed(input):
    embedding = encoder([input])
    return embedding
    # return tf.reshape(embedding, [-1])
    # return embedding

In [34]:
import pandas as pd
import numpy as np
from tqdm import tqdm
tqdm.pandas()
# from get_vector import embed, get_similarity
import scipy.spatial
import tensorflow as tf
stories = pd.read_csv('stories_with_summary.csv')
trope_examples = pd.read_csv('trope_examples.csv')
trope_examples = trope_examples.dropna()
print("read csvs")

read csvs


In [35]:
trope_examples_df = trope_examples[:10]

In [36]:
trope_examples_df

Example trope_id example_type
0  In A Bad Day For Voodoo,  Esmeralda, the maker...   t22727          lit
1  When Tyler tries to   chase after his stolen c...   t01294          lit
2  Esmeralda, the maker of the voodoo dolls, expl...   t22727          lit
3  Tyler is the protagonist, and always tries to ...   t01080          lit
4  Esmeralda the doll-maker tells  Tyler  and  Ke...   t25818          lit
5  Defied. Tyler assures the reader that he is te...   t24933          lit
6  After Adam gets a voodoo doll made of Tyler to...   t08393          lit
7  Implied. As pagan gods are in truth, the disem...   t00608          lit
8  Casper was so nicknamed after the ghost. He's ...   t13853          lit
9  Simon Darcourt is named after a character in C...   t20214          lit

In [37]:
trope_examples = trope_examples_df['Example'][:10].tolist()

In [38]:
trope_examples

['In A Bad Day For Voodoo,  Esmeralda, the maker of the voodoo dolls, explains to Tyler and Kelley that Adam is this, and will one day defeat the hobgoblins. When Kelley questions this, she explains that only the chosen one could have made the voodoo dolls so powerful.',
 'When Tyler tries to   chase after his stolen car which has the voodoo doll of himself in it , he curses  "S-word, f-word, s-word, d-word, s-word times three, f-word, and a z-word that [he] made up on the spot".',
 'Esmeralda, the maker of the voodoo dolls, explains to  Tyler  and  Kelley  that  Adam  is this, and will one day defeat the hobgoblins. When Kelley questions this, she explains that only the chosen one could have made the voodoo dolls so powerful.',
 'Tyler is the protagonist, and always tries to do the right thing, but states to the reader that he is definitely not a role model.',
 'Esmeralda the doll-maker tells  Tyler  and  Kelley ,  "[ Adam ] add to power of doll. Make it super-magical. He  Chosen One 

In [14]:
matrix = encoder(trope_examples)
matrix.shape

TensorShape([10, 512])

In [39]:
# Initialize an empty list to store embedding matrices
embedding_matrices = []
batch_size = 4
# Split the list of strings into batches
for i in range(0, len(trope_examples), batch_size):
    batch = trope_examples[i:i + batch_size]
    print(batch)
    # Encode the batch of strings
    embeddings = encoder(batch)
    
    # Convert the embeddings to a NumPy array
    embeddings = np.array(embeddings)
    
    # Append the batch's embeddings to the list
    embedding_matrices.append(embeddings)

# Combine the embedding matrices from all batches
final_embeddings = np.concatenate(embedding_matrices, axis=0)
print(final_embeddings.shape)

['In A Bad Day For Voodoo,  Esmeralda, the maker of the voodoo dolls, explains to Tyler and Kelley that Adam is this, and will one day defeat the hobgoblins. When Kelley questions this, she explains that only the chosen one could have made the voodoo dolls so powerful.', 'When Tyler tries to   chase after his stolen car which has the voodoo doll of himself in it , he curses  "S-word, f-word, s-word, d-word, s-word times three, f-word, and a z-word that [he] made up on the spot".', 'Esmeralda, the maker of the voodoo dolls, explains to  Tyler  and  Kelley  that  Adam  is this, and will one day defeat the hobgoblins. When Kelley questions this, she explains that only the chosen one could have made the voodoo dolls so powerful.', 'Tyler is the protagonist, and always tries to do the right thing, but states to the reader that he is definitely not a role model.']
['Esmeralda the doll-maker tells  Tyler  and  Kelley ,  "[ Adam ] add to power of doll. Make it super-magical. He  Chosen One .",

In [110]:
# trope_examples['embed'] = trope_examples['Example'].progress_apply(embed)

In [111]:
# trope_examples['embed'][0]

In [112]:
# tf.convert_to_tensor(trope_examples['embed'])

In [40]:
story = stories.iloc[1]
story_embed = embed(story['story'])
# story_embed = tf.reshape(story_embed, [-1])

In [41]:
story_embed

<tf.Tensor: shape=(1, 512), dtype=float32, numpy=
array([[ 9.98608302e-03,  1.00287668e-01, -4.64441404e-02,
        -8.06814060e-02,  1.92088052e-03,  5.30225262e-02,
        -3.28591652e-02, -4.25650552e-02, -5.15515469e-02,
        -6.43923879e-02, -4.62142751e-02,  1.19410958e-02,
         2.72512808e-02, -4.09274781e-03,  2.00058445e-02,
        -1.53025687e-02,  9.02118310e-02, -1.98001005e-02,
        -5.84989861e-02,  8.78998488e-02, -5.68961501e-02,
        -4.02867682e-02, -3.49726677e-02,  3.04025803e-02,
        -4.87671681e-02, -3.95010684e-05,  1.67070422e-02,
         3.07626184e-02,  6.45898134e-02, -2.61449460e-02,
        -2.98817623e-02, -2.15733312e-02, -1.68208173e-03,
        -1.89029537e-02,  6.42244443e-02, -8.92820805e-02,
        -4.34228294e-02, -6.09088689e-02, -1.89149268e-02,
        -7.60356486e-02, -1.65849067e-02, -3.90428398e-03,
         4.88775447e-02, -2.55911518e-02, -7.48986751e-02,
         1.23752514e-02,  4.11232971e-02, -5.21686338e-02,
      

In [42]:
story_embed.shape

TensorShape([1, 512])

In [116]:
# trope_embed_matrix = trope_examples['embed'].to_numpy()

In [117]:
# trope_embed_matrix.flatten().shape

In [118]:
# trope_examples['embed'][0].shape

In [119]:
# trope_embed_matrix = trope_embed_matrix.reshape((2,1))
# trope_embed_matrix.shape

In [43]:
story_embed = np.tile(story_embed, (final_embeddings.shape[0],1))
print(story_embed.shape)
# story_embed = story_embed.reshape((2,1))
# call scipy cdist
similarity = 1 - scipy.spatial.distance.cdist(matrix, story_embed, 'cosine')
print(similarity.shape)
print(similarity)
# get one row
# add it to df
trope_examples_df[story.sid] = similarity[:,0]
trope_examples_df

(10, 512)
(10, 10)
[[ 0.12107358  0.12107358  0.12107358  0.12107358  0.12107358  0.12107358
   0.12107358  0.12107358  0.12107358  0.12107358]
 [ 0.17093187  0.17093187  0.17093187  0.17093187  0.17093187  0.17093187
   0.17093187  0.17093187  0.17093187  0.17093187]
 [ 0.11753389  0.11753389  0.11753389  0.11753389  0.11753389  0.11753389
   0.11753389  0.11753389  0.11753389  0.11753389]
 [ 0.15298812  0.15298812  0.15298812  0.15298812  0.15298812  0.15298812
   0.15298812  0.15298812  0.15298812  0.15298812]
 [ 0.09229994  0.09229994  0.09229994  0.09229994  0.09229994  0.09229994
   0.09229994  0.09229994  0.09229994  0.09229994]
 [ 0.14185904  0.14185904  0.14185904  0.14185904  0.14185904  0.14185904
   0.14185904  0.14185904  0.14185904  0.14185904]
 [ 0.17081197  0.17081197  0.17081197  0.17081197  0.17081197  0.17081197
   0.17081197  0.17081197  0.17081197  0.17081197]
 [-0.0299184  -0.0299184  -0.0299184  -0.0299184  -0.0299184  -0.0299184
  -0.0299184  -0.0299184  -0.0299

Example trope_id example_type  \
0  In A Bad Day For Voodoo,  Esmeralda, the maker...   t22727          lit   
1  When Tyler tries to   chase after his stolen c...   t01294          lit   
2  Esmeralda, the maker of the voodoo dolls, expl...   t22727          lit   
3  Tyler is the protagonist, and always tries to ...   t01080          lit   
4  Esmeralda the doll-maker tells  Tyler  and  Ke...   t25818          lit   
5  Defied. Tyler assures the reader that he is te...   t24933          lit   
6  After Adam gets a voodoo doll made of Tyler to...   t08393          lit   
7  Implied. As pagan gods are in truth, the disem...   t00608          lit   
8  Casper was so nicknamed after the ghost. He's ...   t13853          lit   
9  Simon Darcourt is named after a character in C...   t20214          lit   

         s1  
0  0.121074  
1  0.170932  
2  0.117534  
3  0.152988  
4  0.092300  
5  0.141859  
6  0.170812  
7 -0.029918  
8  0.017042  
9  0.059883

In [44]:
cosine_similarities = tf.reduce_sum(tf.multiply(final_embeddings, story_embed), axis=1)
cosine_similarities
trope_examples_df['tfsim'] = cosine_similarities
trope_examples_df

Example trope_id example_type  \
0  In A Bad Day For Voodoo,  Esmeralda, the maker...   t22727          lit   
1  When Tyler tries to   chase after his stolen c...   t01294          lit   
2  Esmeralda, the maker of the voodoo dolls, expl...   t22727          lit   
3  Tyler is the protagonist, and always tries to ...   t01080          lit   
4  Esmeralda the doll-maker tells  Tyler  and  Ke...   t25818          lit   
5  Defied. Tyler assures the reader that he is te...   t24933          lit   
6  After Adam gets a voodoo doll made of Tyler to...   t08393          lit   
7  Implied. As pagan gods are in truth, the disem...   t00608          lit   
8  Casper was so nicknamed after the ghost. He's ...   t13853          lit   
9  Simon Darcourt is named after a character in C...   t20214          lit   

         s1     tfsim  
0  0.121074  0.121074  
1  0.170932  0.170932  
2  0.117534  0.117534  
3  0.152988  0.152988  
4  0.092300  0.092300  
5  0.141859  0.141859  
6  0.170812  0.170812  
7 -0.029918 -0.029918  
8  0.017042  0.017042  
9  0.059883  0.059883

In [32]:
similarity.shape

(10, 1000)

In [124]:
story_embed = np.tile(story_embed, (matrix.shape[0],1))
# story_embed = story_embed.reshape((2,1))
# call scipy cdist
similarity = 1 - scipy.spatial.distance.cdist(matrix, story_embed, 'cosine')
# get one row
# add it to df
trope_examples[story.sid] = similarity[:,0]

In [125]:
similarity

array([[0.12107358, 0.12107358, 0.12107358, 0.12107358],
       [0.17093189, 0.17093189, 0.17093189, 0.17093189]])

In [126]:
trope_examples

Example trope_id example_type  \
0  In A Bad Day For Voodoo,  Esmeralda, the maker...   t22727          lit   
1  When Tyler tries to   chase after his stolen c...   t01294          lit   

         s1  
0  0.121074  
1  0.170932

In [123]:
print(matrix.shape)
print(story_embed.shape)

(2, 512)
(2, 512)


In [120]:
# story_embed.reshape((512,1))

In [127]:
story_embed = np.tile(story_embed, (matrix.shape[0],1))

In [132]:
print(story_embed.shape)

(1, 512)


In [99]:
similarity = 1 - scipy.spatial.distance.cdist(matrix, story_embed, 'cosine')

In [100]:
similarity

array([[0.12107358, 0.12107358],
       [0.17093189, 0.17093189]])

In [133]:
cosine_similarities = tf.reduce_sum(tf.multiply(matrix, story_embed), axis=1)
cosine_similarities

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.12107359, 0.1709319 ], dtype=float32)>

In [134]:
trope_examples['tfsim'] = cosine_similarities

In [135]:
trope_examples

Example trope_id example_type  \
0  In A Bad Day For Voodoo,  Esmeralda, the maker...   t22727          lit   
1  When Tyler tries to   chase after his stolen c...   t01294          lit   

         s1     tfsim  
0  0.121074  0.121074  
1  0.170932  0.170932